### ISSUE TITLE
Four Step Repository Revival Plan

### ISSUE THREAD

**Issue by sammyhori** [sammyhori/awesome-for-beginners#41]
This issue outlines the plan for reviving this repository (or the repository it's forked from) after a while of inactivity.

**Tasks:**

- [ ] Remove old, outdated things from the template

- [ ] Work through the current list and remove anything no longer valid

- [ ] Review and merge all valid pull requests from the source repository
_Status: All 125 PRs have been looked at and reviewed, almost all approved ones have been merged in_
- [ ] Review and act on all correctly actionable issues from the source repository
